defaults:
  - base_eval
  - _self_

cluster:
  num_nodes: 1
  component_placement:
    actor,reward: all
    rollout: all

runner:
  experiment_name: r1_gisa_markdown
  output_dir: /mnt/project_rlinf/xzxuan/WideSeek-R2/suheng/logs/eval
  seq_length: 32000

  max_epochs: 1
  max_steps: -1

algorithm:
  group_size: 8

agentloop:
  workflow: mas
  add_few_shot: False
  max_sa_turns: 48
  max_planner_turns: 8
  max_worker_turns: 16
  max_workers_per_planner: 8
  max_toolcall_per_worker: 6
  use_llm_judge: True
  use_local_judge: False
  llm_ip: 172.27.233.122
  llm_port: 30000

rollout:
  model:
    model_path: /mnt/project_rlinf/xzxuan/model/Qwen3-4B

tools:
  online: True
  use_jina: True
  use_access_summary: True
  enable_cache: True
  cache_file: "./webpage_cache.json"

data:
  type: wideseek_r1
  max_prompt_length: 4096
  val_rollout_batch_size: 20
  prompt_key: question
  answer_key: answer
  is_markdown: True
  is_hybrid: False
  is_gisa: True
  unique_columns: unique_columns
  validation_shuffle: False
  val_data_paths: /mnt/project_rlinf/xzxuan/WideSeek-R2/suheng/data/gisa_full373_markdown.jsonl
  data_size: -1
