defaults:
  - base_eval

cluster:
  num_nodes: 1
  component_placement:
    actor,reward: all
    rollout: all

runner:
  experiment_name: ws_online_infinite_subagent
  output_dir: ./logs/eval
  seq_length: 32000  

  max_epochs: 1
  max_steps: -1  

algorithm:
  group_size: 4

agentloop:
  workflow: mas # or sa, mas refers to multi-agent, sa refers to single-agent
  llm_ip: 172.27.214.151 # TODO:(USER) Replace with the actual IP address of the LLM judge server
  llm_port: 30000 # TODO:(USER) Replace with the actual port of the LLM judge server
  use_local_judge: False # Whether to use the RLinf internal judge llm. If set to true, the judge llm will be run within RLinf framwork. Otherwise, the judge llm will be run on the external server.
  max_workers_per_planner: -1

rollout:
  model:
    model_path: /mnt/project_rlinf/xzxuan/model/Qwen3-4B # TODO:(USER) Replace with the actual path to the model checkpoint

tools:
  online: False

data:
  type: wideseek_r2
  max_prompt_length: 4096
  val_rollout_batch_size: 128
  prompt_key: question
  answer_key: answer
  answer_type: table
  norm_column: False
  unique_columns: unique_columns 
  validation_shuffle: False
  val_data_paths: /mnt/project_rlinf/xzxuan/wideseek-train_data/width_20k.jsonl # TODO:(USER) Replace with the actual path to the evaluation dataset
  data_size: 128
